# Generated by Django 4.1.7 on 2023-02-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRequisitoPrevioVehicular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('año', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRequisitoPrevioVehicular.vehiculo')),
            ],
        ),
    ]
