# Generated by Django 4.1.7 on 2023-02-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRequisitoPrevioVehicular', '0002_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.CharField(max_length=50),
        ),
    ]
