# Generated by Django 4.1.7 on 2023-03-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRequisitoPrevioVehicular', '0003_alter_vehiculo_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.IntegerField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.CharField(max_length=250),
        ),
    ]
