# Generated by Django 4.1.7 on 2023-03-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRequisitoPrevioVehicular', '0004_alter_vehiculo_año_alter_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.CharField(max_length=50),
        ),
    ]
