# Generated by Django 4.1 on 2023-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRequisitoPrevioVehicular', '0005_alter_vehiculo_año_alter_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
